name: My First GitHub Action Workflow

on: [push]

jobs:
    first-action-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Executing sheel script
              run: ./scripts/ascii-script.sh