name: My First GitHub Action Workflow

on: [push]

jobs:
    first-action-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: List and Read files
              run: |
                echo "Welcome to my first GitHub Action Workflow!"
                ls -lha
                cat README.md || echo "README.md not found"

            - name: Install cowsay
              run: sudo apt-get install -y cowsay

            - name: Generate ASCII Artwork
              run: cowsay -f dragon "Run for cover, Iam a DRAGON... RAWR" >> dragon.txt